[package]
name = "protoc-gen-luau"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.2"                                                           # TODO: maybe overkill and not necessary vs plain match
heck = "0.4.1"
pathdiff = "0.2.1"
prost = "0.12.3"
prost-types = "0.12.3"
stylua = { version = "0.20.0", default-features = false, features = ["luau"] }
