[package]
name = "protobuf-luau" # TODO: rename to protoc-gen-luau
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["conformance"]

[workspace.dependencies]
prost = "0.12.3"
prost-build = "0.12.3"
prost-types = "0.12.3"

[dependencies]
color-eyre = "0.6.2"               # TODO: maybe overkill and not necessary vs plain match
pathdiff = "0.2.1"
prost = { workspace = true }
prost-types = { workspace = true }
